input_datetime:
  jenny_alarm_time:
    has_date: false
    has_time: true

automation:
  - id: '18af6587-36ed-4b41-8e61-117ee86a1f68'
    alias: Jenny Wake up
    trigger:
      platform: time
      at: input_datetime.jenny_alarm_time
    action:
      - service: spotcast.start
        data:
          uri: !secret jennys_wake_up_playlist
          random_song: true
          shuffle: true
          repeat: context
          entity_id: media_player.bedroom_speaker
      - service: media_player.volume_set
        entity_id: media_player.bedroom_speaker
        data:
          volume_level: 0.8
      - service: light.turn_on
        entity_id:
          - light.sitting_room_light
          - light.sink_light
          - light.vestibule_light
          - light.landing_light
          - light.cooker_light
      - service: switch.turn_on
        entity_id:
        - switch.immersion_heater
      - delay:
          minutes: 30
      - service: light.turn_on
        entity_id:
          - light.jennys_bedside_light