input_datetime:
  jenny_alarm_time:
    has_date: false
    has_time: true

automation:
  - id: '18af6587-36ed-4b41-8e61-117ee86a1f68'
    alias: Jenny Wake up
    trigger:
      platform: time
      at: input_datetime.jenny_alarm_time
    action:
      - service: light.turn_on
        target:
          entity_id:
            - light.sitting_room_light
            - light.sink_light
            - light.vestibule_light
            - light.landing_light
            - light.cooker_light
        continue_on_error: true
      - delay:
          minutes: 30
      - service: light.turn_on
        target:
          entity_id:
            - light.jennys_bedside_light
