input_select:
  den_lights_effect:
    name: Den
    options:
      - None
      - Confetti Colour
      - Glitter Colour
      - Juggle Colour
      - Sinelon Colour
      - Christmas
      - Candy Cane
      - Holly Jolly
      - Valentine
      - Lovey Day
      - Saint Patrick
      - Easter
      - USA
      - Independence
      - Go Blue
      - Hail
      - Touchdown
      - Halloween
      - Punkin
      - Thanksgiving
      - Turkey Day
      - BPM
      - Cyclon Rainbow
      - Dots
      - Fire
      - Lightning
      - Police All
      - Police One
      - Rainbow
      - Glitter Rainbow
      - Ripple
      - Twinkle
      - Audio Colour
      - Audio Level Rainbow
      - Audio Random Flash
      - Sunrise
      - Sunset
      - Night Light
      - Daylight
      - Solid Colour

automation:
  - id: 'a7172571-80cb-47f3-9739-14e0223901ca'
    alias: set den effect from input_select
    trigger:
      platform: state
      entity_id: input_select.den_lights_effect
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: input_select.den_lights_effect
          state: None
    action:
      service: light.turn_on
      entity_id: light.emma_led
      data:
        effect: "{{states('input_select.den_lights_effect')}}"

  - id: 'e3159faa-7f78-4a49-8374-a0c0b861db7f'
    alias: set den effect input_select from light
    trigger:
      platform: state
      entity_id: light.emma_led
    action:
      service: input_select.select_option
      entity_id: input_select.den_lights_effect
      data:
        option: "{{state_attr('light.emma_led','effect')}}"
