automation:
  - id: 'dff52442-3c7e-4e23-9396-4baa97cf2d78'
    alias: Alarm Shut Off
    trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      from: 'triggered'
      to: 'disarmed'
    action:
    - service: media_player.turn_off
      entity_id: all
    - service: notify.mobile_app_jenny_s_phone
      data:
        message: clear_notification
        data:
          tag: alarm
          ttl: 0
          visibility: public
          priority: high
          channel: alarm_stream
