automation:
  - id: 'bfe22989-0b04-4e93-93da-a565b46f6aa3'
    alias: Alarm triggered actions
    trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: triggered
    action:
    - service: homeassistant.turn_on
      entity_id: light.all_lights
    - service: light.turn_on
      data:
        entity_id:
          - light.breakfast_bar_led
          # - light.shed_led  *** THIS NEEDS SORTING ***
          - light.emma_led
        effect: "Police All"
        brightness: 100
    - service: notify.mobile_app_jenny_s_phone
      data:
        message: 'ALARM! The alarm has been triggered: {{ states.input_text.alarm_trigger.state }}'
        title: 'Home Alarm'
        data:
          ttl: 0
          visibility: public
          priority: high
          channel: alarm_stream
          vibrationPattern: "100, 1000, 100, 1000"
          importance: max
          persistent: true
          sticky: true
          image: www/pics/sitting_room_alarm.jpg
          tag: alarm
          color: 'red'
          clickAction: 'lovelace/cctv'
    - service: media_player.turn_on
      entity_id: media_player.living_room_speaker
    - service: media_player.volume_set
      data:
        entity_id: media_player.living_room_speaker
        volume_level: 1
    - service: tts.google_translate_say
      data:
        message: 'The Alarm has been triggered'
        entity_id: all
    - service: media_player.play_media
      data:
        entity_id: media_player.living_room_speaker
        media_content_id: !secret alarm_media
        media_content_type: mp3
    - service: notify.email_jenny
      data:
        title: 'Alarm Triggered'
        message: "ALARM! The alarm has been triggered: {{ states.input_text.alarm_trigger.state }}"
        data:
          images:
            - 'www/pics/sitting_room_alarm.jpg'
    - service: script.alarm_notifications
