automation:
  - id: 'cb36036e-5826-4251-85d9-a1e3b1f71e2c'
    alias: Alarm Trigger - Night mode
    trigger:
    # panic button
    - platform: state
      entity_id: input_boolean.panic_button
    # downstairs light switches
    #- platform: state
    #  entity_id: binary_sensor.sitting_room_light_switch
    #- platform: state
    #  entity_id: binary_sensor.vestibule_light_switch
    #- platform: state
    #  entity_id: binary_sensor.cooker_light_switch
    #- platform: state
    #  entity_id: binary_sensor.sink_light_switch  
    #- platform: state
    #  entity_id: binary_sensor.bathroom_light_switch 
      ##############
      #   Doors
      ##############
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
    - platform: state
      entity_id: binary_sensor.back_door
      to: 'on'
      ##############
      #   Windows
      ##############
    - platform: state
      entity_id: binary_sensor.kitchen_window
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_window
      to: 'on'
    - platform: state
      entity_id: binary_sensor.emmas_window
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bedroom_window
      to: 'on'
      #   Downstairs Motion
    - platform: state
      entity_id: binary_sensor.sitting_room_sensor_pir
      to: 'on'
    #- platform: state
    #  entity_id: binary_sensor.kitchen_sensor_pir
    #  to: 'on'
    - platform: state
      entity_id: binary_sensor.downstairs_motion
      to: 'on'
    #- platform: state
    #  entity_id: binary_sensor.vestibule_motion
    #  to: 'on'
    condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: 'armed_night'
    - condition: template
      value_template: >
        {{ trigger.from_state != 'unavailable' and
            trigger.to_state != 'unavailable' }}
    action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm
    - service: input_text.set_value
      data_template:
        entity_id: input_text.alarm_trigger
        value: >
          {% if states.input_text.alarm_trigger.state|length == 0 %}
            {{ trigger.from_state.attributes.friendly_name }}
          {% elif (states.input_text.alarm_trigger.state|length + trigger.from_state.attributes.friendly_name|length) < 100 %}
            {{ states.input_text.alarm_trigger.state }}, {{ trigger.from_state.attributes.friendly_name }}
          {% else %}
            {{ states.input_text.alarm_trigger.state }}
          {% endif %}