fallback_password: fallback_password
3dprinter_psu_pwd: 3d_printer_psu_pwd
ap-password: apPassword

#### IP Addresses
doorbell_ip: 1.1.1.1
vestibule_light_ip: 1.1.1.1
home-assistant-glow_ip: 1.1.1.1
sitting_room_light_ip: 1.1.1.1
sitting_room_wall_light_ip: 1.1.1.1
temp_hub_ip: 1.1.1.1
ir-blaster_ip: 1.1.1.1
sonoff_rf_bridge_ip: 1.1.1.1
ttgo_sitting_room_sensor_ip: 1.1.1.1
3d_printer_psu_ip: 1.1.1.1
cooker_light_ip: 1.1.1.1
sink_light_ip: 1.1.1.1
immersion_ip: 1.1.1.1
kitchen_socket_2_ip: 1.1.1.1
kitchen_socket_1_ip: 1.1.1.1
bathroom_light_ip: 1.1.1.1
landing_light_ip: 1.1.1.1
emmas_ceiling_light_ip: 1.1.1.1
emmas_bedside_light_ip: 1.1.1.1
bedroom_ceiling_light_ip: 1.1.1.1
jennys_bedside_light_ip: 1.1.1.1
carmels_bedside_light_ip: 1.1.1.1
carmels_control_panel_ip: 1.1.1.1
leopard_gecko_temp_and_light_ip: 1.1.1.1
quail_cage_ip: 1.1.1.1
