spotcast:
  sp_dc: !secret spotify_jenny_sp_dc
  sp_key: !secret spotify_jenny_sp_key
  accounts:
    emma:
      sp_dc: !secret spotify_emma_sp_dc
      sp_key: !secret spotify_emma_sp_key

sensor:
  - platform: spotcast

script:
  play_spotify_playlist:
    alias: Play Spotify Playlist
    description: "Starts playing a spotify playlist and set volume"
    mode: queued
    sequence:
      - service: spotcast.start
        data:
          uri: '{{ uri }}'
          account: '{{ account }}'
          random_song: '{{random_song}}'
          shuffle: '{{shuffle}}'
          repeat: '{{repeat}}'
          entity_id: '{{entity_id}}'
      - service: media_player.volume_set
        data:
          entity_id: '{{entity_id}}'
          volume_level: '{{volume_level}}'
