input_datetime:
  emma_alarm_time:
    has_date: false
    has_time: true

automation:
  - id: 'b8c303dd-ecea-465d-bd06-4c4f039548da'
    alias: Emma Wake up
    trigger:
      platform: time
      at: input_datetime.emma_alarm_time
    action:
      - service: spotcast.start
        data:
          uri: spotify:playlist:012tC1TIzdDg060DtIT7nE
          random_song: true
          shuffle: true
          account: emma
          entity_id: media_player.emma_s_room_speaker
          start_volume: 50
        continue_on_error: true
      - service: light.turn_on
        entity_id:
          - light.emmas_ceiling_light
          - light.emmas_bedside_light
