rest_command:
  update_ionos_domains:
    url: !secret ionos_ddns_url

automation:
  - id: 'f1b23b8a-9cb8-41fd-baa3-27f7f2ebdf4e'
    alias: update DDNS records
    trigger:
      - platform: state
        entity_id: sensor.myip
      - platform: homeassistant
        event: start
    condition:
    - condition: template
      value_template: >
        {{ trigger.to_state != 'unavailable' }}
    action:
      - service: rest_command.update_ionos_domains
