anniversaries:
  sensors:
  - name: Carmel's Birthday
    date: !secret carmel_birthday

automation:
  - id: '637882ac-7024-465d-b528-e043c0e39726'
    alias: Carmel's Birthday Greeting
    trigger:
      platform: time
      at: "15:50:00"
    condition:
      - condition: state
        entity_id: sensor.anniversary_carmel_s_birthday
        state: '0'
    action:
      - service: notify.mobile_app_jenny_s_phone
        data:
          message: "Happy Birthday To Carmel!"
          data:
            tag: birthday
      - service: notify.google_assistant_sdk
        data:
          message: "Happy Birthday Carmel!"
