anniversaries:
  sensors:
  - name: Jenny's Birthday
    date: !secret jenny_birthday

automation:
  - id: 'd877354b-ffb5-4076-b5b8-472e4a210860'
    alias: Jenny's Birthday Greeting
    trigger:
      platform: time
      at: "15:50:00"
    condition:
      - condition: state
        entity_id: sensor.anniversary_jenny_s_birthday
        state: '0'
    action:
      - service: notify.mobile_app_jenny_s_phone
        data:
          message: "Happy Birthday Jenny!"
          data:
            tag: birthday
      - service: notify.google_assistant_sdk
        data:
          message: "Happy Birthday Jenny!"
