automation:
  - id: 'e72e5e02-8e97-43c2-a3d4-e752017df4ee'
    alias: Wake Up For School
    trigger:
      - at: '07:00:00'
        platform: time
    condition:
      condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      - service: light.turn_on
        target:
          entity_id:
            - light.sitting_room_light
            - light.sink_light
            - light.landing_light
            - light.emmas_ceiling_light
        continue_on_error: true
      - service: spotcast.start
        data:
          uri: spotify:playlist:012tC1TIzdDg060DtIT7nE
          random_song: true
          shuffle: true
          account: emma
          entity_id: media_player.emma_s_room_speaker
          start_volume: 50
        continue_on_error: true
