automation:
  - id: 'dc151c2b-87ae-43fa-89fd-597409f47b72'
    alias: Night - Return home lights
    trigger:
    - entity_id: person.jenny_gorton
      from: not_home
      platform: state
    - entity_id: person.emma_gorton
      from: not_home
      platform: state
    condition:
    - after: 01:00
      condition: time
    - before: sunrise
      condition: sun
    action:
    - service: light.turn_on
      entity_id:
      - light.vestibule_light
      - light.sitting_room_light