automation:
  - id: 'eaa1418c-1e48-4a08-9779-58ed8c71128a'
    alias: Evening - Sitting Room wall light on 2 hours before sunset
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: light.movie_mode_lights
            state: 'off'
          - condition: state
            entity_id: light.sitting_room_light
            state: 'off'
    trigger:
      - event: sunset
        offset: '-2:00'
        platform: sun
    action:
      - service: light.turn_on
        entity_id:
          - light.sitting_room_wall_lights
      - condition: numeric_state
        entity_id: sensor.vestibule_temperature
        below: 15
      - service: light.turn_on
        entity_id:
          - light.flame_lantern
