automation:
  - id: '04e4777d-2738-4c88-979b-7410ff41f89f'
    alias: Night - Upstairs lights off at 1:30
    trigger:
    - platform: time
      at: 01:30
    condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: 'armed_away'
    action:
    - service: light.turn_off
      entity_id: light.upstairs_lights
