automation:
  - id: 'f47e81e2-d138-4226-b0fc-0364671613c9'
    alias: Emma at Nia's
    trigger:
    - platform: zone
      entity_id: person.emma_gorton
      zone: zone.nia_s_house
      event: enter
    action:
    - service: notify.mobile_app_jenny_s_phone
      data:
        message: Emma has arrived at Nia's
        title: Emma Location
        data:
          tag: emma_location

  - id: 'dbfc30bd-5e48-4bcc-b980-a695442b1aa7'
    alias: Emma left Nia's
    trigger:
    - platform: zone
      entity_id: person.emma_gorton
      zone: zone.nia_s_house
      event: leave
    action:
    - service: notify.mobile_app_jenny_s_phone
      data:
        message: Emma has Left Nia's
        title: Emma Location
        data:
          tag: emma_location
