automation:
  - id: '21d1a683-8d42-44c2-8cfa-3f94e769d9ea'
    alias: Emma home
    trigger:
    - platform: zone
      entity_id: person.emma_gorton
      zone: zone.home
      event: enter
    action:
    - service: notify.mobile_app_jenny_s_phone
      data:
        title: Emma Location
        message: Emma has arrived home
        data:
          tag: emma_location
    - service: notify.google_assistant_sdk
      data:
        message: 'Emma is home!'

  - id: 'fb86e809-5d31-4505-8949-360413654c6b'
    alias: Emma left home
    trigger:
    - platform: zone
      entity_id: person.emma_gorton
      zone: zone.home
      event: leave
    action:
    - service: notify.mobile_app_jenny_s_phone
      data:
        title: Emma Location
        message: Emma has Left The House
        data:
          tag: emma_location
    - service: notify.google_assistant_sdk
      data:
        message: 'Emma has Left The House!'
