automation:
  - id: '9709ecab-deec-41a6-87e1-af9e75ea497c'
    alias: Emma at Agatha's
    trigger:
      - platform: zone
        entity_id: person.emma_gorton
        zone: zone.agatha_s_house
        event: enter
    action:
    - service: notify.mobile_app_jenny_s_phone
      data:
        message: Emma has arrived at Agatha's
        data:
          tag: emma_location

  - id: '79a8f099-61a8-43ab-9f1a-9915df95c196'
    alias: Emma left Agatha's
    trigger:
      - platform: zone
        entity_id: person.emma_gorton
        zone: zone.agatha_s_house
        event: leave
    action:
    - service: notify.mobile_app_jenny_s_phone
      data:
        title: Emma Location
        message: Emma has Left Agatha's House
        data:
          tag: emma_location
