binary_sensor:
  - platform: ping
    host: !secret chickencam_ip
    scan_interval: 60
    name: Chickencam Ping

mqtt:
  binary_sensor:
  - name: chickencam Motion
    state_topic: "cameras/chickencam/motion"
    device_class: motion

automation:
  - id: "0b1207d4-a81a-400b-a8a1-5d0774eab975"
    alias: Chickencam Offline warning
    trigger:
      - platform: state
        entity_id: binary_sensor.chickencam_ping
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
    action:
      choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.chickencam_ping
              state: 'off'
          sequence:
            - service: notify.broadcast_from_home_assistant
              data:
                message: >-
                  {{["It looks like the Chicken Cam is offline",
                  "The Stupid dog has done it again! - The Chicken cam is unplugged",
                  "It looks like Bentley has unplugged the Chicken Cam again!"]| random }}
            - service: notify.mobile_app_jenny_s_phone
              data:
                message: "Chicken Cam is offline"
                title: ChickenCam Error
                data:
                  tag: chicken_cam_offline
      default:
        - service: notify.mobile_app_jenny_s_phone
          data:
            message: clear_notification
            data:
              tag: chicken_cam_offline
