automation:
  - id: '98e9e765-84db-4e25-ac61-b3cbc85b68c3'
    alias: Kitchen LEDs on with Sink light
    trigger:
    - platform: state
      entity_id: light.sink_light
      to: 'on'
    action:
    - service: light.turn_on
      entity_id: light.breakfast_bar_led

  - id: 'd1c5b5c2-3191-46a8-849a-c100c0f24728'
    alias: Kitchen LEDs off with Sink light
    trigger:
    - platform: state
      entity_id: light.sink_light
      to: 'off'
    condition:
      - condition: state
        entity_id: light.movie_mode_lights
        state: 'off'
    action:
    - service: light.turn_off
      entity_id: light.breakfast_bar_led
