sensor:
  - platform: template
    sensors:
      default_led_effect:
        value_template: >-
          {% if is_state("sensor.anniversary_jenny_s_birthday", "0") or
              is_state("sensor.anniversary_carmel_s_birthday", "0") or
              is_state("sensor.anniversary_emma_s_birthday","0") -%}
            Rainbow
          {%- elif is_state("sensor.valentine_s_day","0") -%}
            Lovey Day
          {%- elif is_state("sensor.halloween", "0") -%}
            Punkin
          {%- elif is_state("sensor.guy_fawkes_day", "0") -%}
            Fire
          {%- elif is_state("sensor.st_david_s_day", "0") -%}
            Holly Jolly
          {%- elif is_state("sensor.feast_of_the_immaculate_conception", "0") -%}
            Hail
          {%- elif is_state("sensor.christmas_day","0") or
              is_state("sensor.easter_sunday","0") -%}
            Rainbow
          {%- elif states("sensor.easter_sunday") |int < 47 -%}
            Punkin
          {%- elif states("sensor.christmas_day") |int > 200 and
              states("sensor.epiphany") |int <= 12 -%}
            Holly Jolly
          {%- elif is_state("sensor.first_sunday_of_advent", "0")  or
              (states("sensor.first_sunday_of_advent") |int > 200 and
              states("sensor.christmas_day") |int < 28) -%}
            Punkin
          {%- else -%}
            Solid Color
          {%- endif %}
        attribute_templates:
          color: >-
            {% if states("sensor.date") and now().weekday() == 6 -%}
              {"r":0,"g":255,"b":0}
            {%- else -%}
              {"r":255,"g":255,"b":36}
            {%- endif %}
          speed: >-
            {% if is_state("sensor.default_led_effect", "Rainbow") or
              is_state("sensor.default_led_effect", "Hail") -%}
              135
            {%- elif is_state("sensor.default_led_effect", "Lovey Day") or
              is_state("sensor.default_led_effect", "Fire") -%}
              0
            {%- else -%}
              180
            {%- endif %}

automation:
  - id: '5815b9f6-ac4b-4d3d-b53d-753d66176ef8'
    alias: set default led effect at startup
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: homeassistant.update_entity
        data:
          entity_id: sensor.default_led_effect

  - id: '3a751475-257f-4292-8298-bb4efa720309'
    alias: Auto set Kitchen LEDs
    trigger:
      - platform: state
        entity_id: sensor.default_led_effect
    condition:
      - condition: state
        entity_id: light.movie_mode_lights
        state: 'off'
    action:
      - service: mqtt.publish
        data:
          topic: "cmnd/KitchenLEDs"
          payload_template: >-
            {"brightness":210,
            "effect":"{{states("sensor.default_led_effect")}}",
            "color_temp":{{state_attr("sensor.default_led_effect","speed")}},
            "color": {{state_attr("sensor.default_led_effect","color")}}}

  - id: '7162dacf-eb69-499d-afcf-ce5a05958553'
    alias: Auto set Outside LEDs
    trigger:
      - platform: state
        entity_id: sensor.default_led_effect
    action:
      - service: mqtt.publish
        data:
          topic: "cmnd/OutsideLights"
          payload_template: >-
            {"brightness":4,
            "effect":"{{states("sensor.default_led_effect")}}",
            "color_temp":{{state_attr("sensor.default_led_effect","speed")}},
            "color": {{state_attr("sensor.default_led_effect","color")}}}
