script:
  ender3_safe_power_down:
    alias: Ender3 Safe Power Down
    sequence:
      - condition: state
        entity_id: sensor.ender_3_current_print_state
        state:
          - 'complete'
          - 'standby'
      - service: button.press
        target:
          entity_id: button.ender_3_host_shutdown
      - wait_template: "{{ is_state('sensor.ender_3_current_print_state', 'unavailable') }}"
      - delay:
          seconds: 30
      - service: switch.turn_off
        entity_id: switch.3d_printer_psu

  ender3_shutdown_when_cool:
    alias: Ender3 shutdown when cool
    sequence:
      - condition: state
        entity_id: sensor.ender_3_current_print_state
        state:
          - 'complete'
          - 'standby'
      - wait_template: "{{ states('sensor.ender_3_extruder_temperature')|int < 40  }}"
        timeout: '00:10:00'
        continue_on_timeout: false
      - service: script.ender3_safe_power_down

  ender3_cancel_print:
    alias: Ender3 Cancel
    sequence:
      - condition: state
        entity_id: switch.ender3_controls
        state: 'on'
      - service: button.press
        target:
          entity_id: button.ender_3_cancel_print

  ender3_pause_print:
    alias: Ender3 Pause
    sequence:
      - condition: state
        entity_id: switch.ender3_controls
        state: 'on'
      - service: button.press
        target:
          entity_id: button.ender_3_pause_print

  ender3_resume_print:
    alias: Ender3 Resume
    sequence:
      - condition: state
        entity_id: switch.ender3_controls
        state: 'on'
      - service: button.press
        target:
          entity_id: button.ender_3_resume_print

  ender3_home:
    alias: Ender3 Homing
    sequence:
      - condition: state
        entity_id: switch.ender3_controls
        state: 'on'
      - condition: state
        entity_id: sensor.ender_3_current_print_state
        state:
          - 'standby'
          - 'complete'
        # NOT YET AVAILABLE - ADD Homing

  ender3_level_bed:
    alias: Ender3 Bed Levelling
    sequence:
      - condition: state
        entity_id: switch.ender3_controls
        state: 'on'
      - condition: state
        entity_id: sensor.ender_3_current_print_state
        state:
          - 'standby'
          - 'complete'
          # NOT YET AVAILABLE - ADD BED_MESH_CALIBRATE

  ender3_cooldown:
    alias: Ender3 cooldown
    sequence:
      - condition: state
        entity_id: switch.ender3_controls
        state: 'on'
        # to do add cooling

  ender3_preheat_petg:
    alias: Ender3 PETG Preheat
    sequence:
      - condition: state
        entity_id: switch.ender3_controls
        state: 'on'
        # TO DO add heating

  ender3_preheat_pla:
    alias: Ender3 PLA Preheat
    sequence:
      - condition: state
        entity_id: switch.ender3_controls
        state: 'on'
        # TO DO add heating

  ender3_change_filament:
    alias: Ender3 Filament Change
    sequence:
      - condition: state
        entity_id: switch.ender3_controls
        state: 'on'
        # TO DO add filament change

automation:
  - id: '21c0b61f-1a27-43af-8044-60a83de0eec2'
    alias: Ender 3 Auto shutdown when done
    description: Shutdown the printer once is has cooled down
    trigger:
      - platform: state
        entity_id: sensor.ender_3_current_print_state
        from:
          - 'printing'
          - 'paused'
        to: 'complete'
    action:
      - service: script.ender3_shutdown_when_cool
