switch:
  - platform: template
    switches:
      ender3:
        friendly_name: Ender3
        value_template: "{{ is_state('switch.3d_printer_psu', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.3d_printer_psu
        turn_off:
          service: script.ender3_safe_power_down

homeassistant:
  customize:
    switch.ender3:
      icon: mdi:printer-3d

mqtt:
  switch:
    - name: Ender3 Controls
      optimistic: true
      command_topic: "ender3_controls"

automation:
  - id: '383db63c-ffcc-4b77-90b4-3b0fd04a33c0'
    alias: ender3 disable controls
    trigger:
      - platform: state
        entity_id: switch.ender3_controls
        to: 'on'
    action:
      - delay: '00:02:00'
      - service: switch.turn_off
        entity_id: switch.ender3_controls
