automation:
  - id: 'db89df0b-e16e-4000-a409-3ea52acf2a30'
    alias: Ender3 Notifications
    mode: queued
    trigger:
      - platform: state
        entity_id: sensor.ender_3_current_print_state
        to: 'COMPLETE'
    action:
      - service: notify.mobile_app_jenny_s_phone
        data:
          message: 'Ender 3 Finished'
          title: 3D print finished
          data:
            image: !secret ender3_camera_still
            tag: ender-3
            color: 'green'
