scene:
  - name: Movie Mode
    entities:
      light.movie_mode_lights:
        state: 'on'

light:
  - platform: template
    lights:
      movie_mode_lights:
        friendly_name: "Movie Mode Light"
        value_template: >-
          {{ is_state('light.cooker_light', 'off') and
          is_state('light.sink_light', 'off') and
          is_state('light.sitting_room_light', 'off') and
          is_state('light.vestibule_light', 'off') and
          is_state('light.landing_light', 'off') and
          is_state('light.breakfast_bar_led', 'on') and
          is_state('light.sitting_room_wall_lights', 'on') and
          is_state_attr('light.breakfast_bar_led', 'effect','Solid Color') and
          is_state_attr('light.breakfast_bar_led', 'rgb_color', (10, 255, 10)) and
          is_state_attr('light.breakfast_bar_led', 'brightness', 90)}}
        turn_on:
          - service: light.turn_off
            entity_id: >
              light.cooker_light,
              light.sink_light,
              light.sitting_room_light,
              light.vestibule_light,
              light.landing_light
          - service: light.turn_on
            entity_id: light.sitting_room_wall_lights
          - delay:
              milliseconds: 100
          - service: light.turn_on
            entity_id: light.breakfast_bar_led
            data:
              effect: "Solid Color"
              brightness: 90
              rgb_color: [10, 255, 10]
        turn_off:
          # - service: mqtt.publish
          #   data:
          #     topic: "cmnd/KitchenLEDs"
          #     payload_template: >-
          #       {"brightness":210,
          #       "effect":"{{states("sensor.default_led_effect")}}",
          #       "white_value":{{state_attr("sensor.default_led_effect","speed")}},
          #       "color": {{state_attr("sensor.default_led_effect","color")}}}
          - service: light.turn_on
            data:
              entity_id: light.sink_light

automation:
  - id: '2fbe2413-56e9-4c21-8899-0152e8e04366'
    alias: Reset kitchen LEDs after movie mode
    trigger:
      - platform: state
        entity_id: light.movie_mode_lights
        to: 'off'
    action:    
      - service: mqtt.publish
        data:
          topic: "cmnd/KitchenLEDs"
          payload_template: >-
            {"brightness":210,"effect":"{{states("sensor.default_led_effect")}}"
            ,"white_value":{{state_attr("sensor.default_led_effect","speed")}}
            ,"color":{{state_attr("sensor.default_led_effect","color")}}}
      - condition: state
        entity_id: light.sink_light
        state: 'off'
      - service: light.turn_off
        entity_id: light.breakfast_bar_led
