esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: $friendly_name Touch Switch
    on_press:
      - light.toggle: light_output

  - platform: status
    name: $friendly_name Sonoff Status

  # - platform: gpio
  #   id: dummy
  #   #internal: true
  #   pin:
  #     number: GPIO12
  #   on_press:
  #     - light.turn_off: led
  #   on_release:
  #     - light.turn_on: led

output:
  - platform: gpio
    pin: GPIO12
    id: relay

  # - platform: esp8266_pwm
  #   id: blue_led
  #   pin: GPIO13
  #   inverted: true
  #   max_power: 0.4

light:
  - platform: binary
    id: light_output
    name: $friendly_name
    output: relay

  # - platform: monochromatic
  #   id: led
  #   name: blue led
  #   output: blue_led
  #   # internal: true

sensor:
  - platform: wifi_signal
    name: $friendly_name Sonoff WiFi Signal
    update_interval: 10s
  - platform: uptime
    name: $friendly_name Sonoff Uptime

# status_led:
#   pin:
#     number: GPIO13
#     # inverted: yes

switch:
  - <<: !include switch/reboot.yaml
