automation:
  - id: '3420a209-07e7-4328-9c02-6b002fbfbf3a'
    alias: Garbage Reminder
    trigger:
      platform: time
      at: "19:00:00"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: sensor.general_waste
          state: 'Tomorrow'
        - condition: state
          entity_id: sensor.recycling
          state: 'Tomorrow'
    action:
      - service: notify.mobile_app_jenny_s_phone
        data:
          title: Time to put the rubbish out!
          message: >-
            The {% if is_state("sensor.general_waste", "tomorrow") and is_state("sensor.recycling", "tomorrow") -%}
              Rubbish and Recycling
            {%- elif is_state("sensor.general_waste", "tomorrow") -%}
              Rubbish
            {%- elif is_state("sensor.recycling", "tomorrow") -%}
              Recycling
            {%- endif %} needs to go out
      - condition: zone
        entity_id: person.jenny_gorton
        zone: zone.home
      - service: notify.google_assistant_sdk
        data:
          message: >-
            The {% if is_state("sensor.general_waste", "tomorrow") and is_state("sensor.recycling", "tomorrow") -%}
              Rubbish and Recycling
            {%- elif is_state("sensor.general_waste", "tomorrow") -%}
              Rubbish
            {%- elif is_state("sensor.recycling", "tomorrow") -%}
              Recycling
            {%- endif %} needs to go out
