automation:
  - id: '7ba5889f-44d3-453e-8aff-3455da0f3282'
    alias: Evening - vestibule light on 1 hour before sunset
    trigger:
    - event: sunset
      offset: '-1:00'
      platform: sun
    condition:
      - condition: state
        entity_id: light.movie_mode_lights
        state: 'off'
    action:
    - entity_id: light.vestibule_light
      service: light.turn_on