automation:
  - id: '7202213f-80e5-4ece-ae62-d7958615f2b8'
    alias: github actions webhook
    mode: queued
    trigger:
      platform: webhook
      webhook_id: !secret github_actions_webhook
      local_only: false
    condition: '{{trigger.json.check_run.check_suite.head_branch == "master"}}'
    action:
      - service: mqtt.publish
        data:
          topic: 'github_checkrun/{{ trigger.json.check_run.name}}'
          payload: >
            {"status": {%- if trigger.json.check_run.status == 'completed' -%}
              "{{trigger.json.check_run.conclusion}}"
            {%- else -%}
              "{{trigger.json.check_run.status}}"
            {%- endif -%}, "id": "{{trigger.json.check_run.id
            }}", "started_at": "{{trigger.json.check_run.started_at
            }}", "completed_at": "{{trigger.json.check_run.completed_at
            }}", "details_url": "{{trigger.json.check_run.details_url}}"}
          retain: true

mqtt:
  sensor:
    - name: github_checkrun_home_assistant_beta
      state_topic: github_checkrun/HA beta Config Check
      value_template: "{{ value_json.status }}"
      json_attributes_topic: github_checkrun/HA beta Config Check
      icon: mdi:github

    - name: github_checkrun_esphome
      state_topic: github_checkrun/esphome
      value_template: "{{ value_json.status }}"
      json_attributes_topic: github_checkrun/esphome
      icon: mdi:github

    - name: github_checkrun_remarklint
      state_topic: github_checkrun/Remark Lint
      value_template: "{{ value_json.status }}"
      json_attributes_topic: github_checkrun/Remark Lint
      icon: mdi:github

    - name: github_checkrun_yamllint
      state_topic: github_checkrun/Yaml Lint
      value_template: "{{ value_json.status }}"
      json_attributes_topic: github_checkrun/yamllint
      icon: mdi:github

    - name: github_checkrun_home_assistant_latest_release
      state_topic: github_checkrun/HA stable Config Check
      value_template: "{{ value_json.status }}"
      json_attributes_topic: github_checkrun/HA stable Config Check
      icon: mdi:github

    - name: github_checkrun_home_assistant_current_install
      state_topic: github_checkrun/HA  Config Check
      value_template: "{{ value_json.status }}"
      json_attributes_topic: github_checkrun/HA  Config Check
      icon: mdi:github

    - name: github_checkrun_home_assistant_dev
      state_topic: github_checkrun/HA dev Config Check
      value_template: "{{ value_json.status }}"
      json_attributes_topic: github_checkrun/HA dev Config Check
      icon: mdi:github

rest_command:
  trigger_github_checkruns:
    url: https://api.github.com/repos/pinkywafer/Home-Assistant_Config/actions/workflows/main.yml/dispatches
    method: POST
    headers:
      authorization: !secret github_issue_token
      Accept: "application/vnd.github.v3+json"
    payload: '{"ref":"master"}'
