automation:
  - id: '7202213f-80e5-4ece-ae62-d7958615f2b8'
    alias: github actions webhook
    mode: queued
    trigger:
      platform: webhook
      webhook_id: !secret github_actions_webhook
    condition: '{{trigger.json.check_run.check_suite.head_branch == "master"}}'
    action:
      - service: mqtt.publish
        data:
          topic: 'github_checkrun/{{ trigger.json.check_run.name}}'
          payload: >
            {"status": {%- if trigger.json.check_run.status == 'completed' -%}
              "{{trigger.json.check_run.conclusion}}"
            {%- else -%}
              "{{trigger.json.check_run.status}}"
            {%- endif -%}, "id": "{{trigger.json.check_run.id
            }}", "started_at": "{{trigger.json.check_run.started_at
            }}", "completed_at": "{{trigger.json.check_run.completed_at
            }}", "details_url": "{{trigger.json.check_run.details_url}}"}
          retain: true

sensor:
  - platform: mqtt
    name: github_checkrun_remarklint
    state_topic: github_checkrun/remarklint
    value_template: "{{ value_json.status }}"
    json_attributes_topic: github_checkrun/remarklint

  - platform: mqtt
    name: github_checkrun_yamllint
    state_topic: github_checkrun/yamllint
    value_template: "{{ value_json.status }}"
    json_attributes_topic: github_checkrun/yamllint

  - platform: mqtt
    name: github_checkrun_home_assistant_latest_release
    state_topic: github_checkrun/home_assistant_latest_release
    value_template: "{{ value_json.status }}"
    json_attributes_topic: github_checkrun/home_assistant_latest_release

  - platform: mqtt
    name: github_checkrun_home_assistant_current_install
    state_topic: github_checkrun/home_assistant_current_install
    value_template: "{{ value_json.status }}"
    json_attributes_topic: github_checkrun/home_assistant_current_install

  - platform: mqtt
    name: github_checkrun_home_assistant_beta
    state_topic: github_checkrun/home_assistant_beta
    value_template: "{{ value_json.status }}"
    json_attributes_topic: github_checkrun/home_assistant_beta

  - platform: mqtt
    name: github_checkrun_home_assistant_dev
    state_topic: github_checkrun/home_assistant_dev
    value_template: "{{ value_json.status }}"
    json_attributes_topic: github_checkrun/home_assistant_dev

rest_command:
  trigger_github_checkruns:
    url: https://api.github.com/repos/pinkywafer/Home-Assistant_Config/actions/workflows/main.yml/dispatches
    method: POST
    headers:
      authorization: !secret github_issue_token
      Accept: "application/vnd.github.v3+json"
    payload: '{"ref":"master"}'
