refresh_library:
  name: "Library"
  description: "Rescan/Refresh Tdarr Library"
  fields:
    library:
      name: Library
      description: "Library Name to refresh"
      required: true
      example: "Movies"
      selector:
        text:
    folderpath:
      name: Folder Path
      description: "Library Folder path e.g. /Movies (Have to include this for now)"
      example: "/Movies"
      required: true
      selector:
        text:
    mode:
      name: Scan Mode
      description: "Mode to scan (default find new files only)"
      selector:
        select:
          options:
            - scanFindNew
            - scanFresh

