sensor:
  - platform: youtube
    channel_id: UCVpankR4HtoAVtYnFDUieYA
  
  - platform: socialblade
    name: zefrank1_info
    channel_id: UCVpankR4HtoAVtYnFDUieYA

automation:
  - id: '6fe8bf58-7300-4fb4-8a6c-df52dad4b552'
    alias: YouTube Notification - zefrank1
    trigger:
      - platform: state
        entity_id: sensor.zefrank1
    action:
    - service: notify.mobile_app_jenny_s_oppo_reno
      data:
        message: '{{ states("sensor.zefrank1")}}'
        title: >
          {% if is_state_attr("sensor.zefrank1", "live", False) -%}
          'New zefrank1 Video Available'
          {%- else -%}
          'zefrank1 is Live!'
          {%- endif %}
        data:
          image: "{{state_attr('sensor.zefrank1','entity_picture')}}"
          tag: zefrank1
          color: 'green'
          actions:
            - action: "URI"
              title: "Watch Now"
              uri: '{{ state_attr("sensor.zefrank1","url") }}'