input_datetime:
  collect_carmel_time:
    has_date: false
    has_time: true

automation:
  - id: '123f0ad4-1b31-4080-bf7f-ea6ba4182c1a'
    alias: Collect Carmel
    description: ''
    trigger:
    - platform: time
      at: input_datetime.collect_carmel_time
    condition:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    action:
    - service: notify.broadcast_from_home_assistant
      data:
        message: It's time to go
    mode: single
