substitutions:
  ip_address: !secret carmels_control_panel_ip
  reboot_time: 10min
  devicename: carmels-control-panel
  friendly_name: Carmel's Control Panel

packages:
  wifi: !include common/wifi.yaml

esphome:
  name: $devicename
  platform: ESP32
  board: esp-wrover-kit

  # Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:

bluetooth_proxy:
  active: true

binary_sensor:
  - <<: !include common/binary_sensor/status.yaml

  - platform: gpio
    pin:
      number: 23
      mode: INPUT_PULLUP
      inverted: true
    name: "Carmel's Green switch"
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms

  - platform: gpio
    pin:
      number: 22
      mode: INPUT_PULLUP
      inverted: true
    name: "Carmel's Orange switch"
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms

  - platform: gpio
    pin:
      number: 21
      mode: INPUT_PULLUP
      inverted: true
    name: "Carmel's Red switch"
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms

  - platform: gpio
    pin:
      number: 19
      mode: INPUT_PULLUP
      inverted: true
    name: "Carmel's Blue switch"
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms

  - platform: gpio
    pin:
      number: 18
      mode: INPUT_PULLUP
      inverted: true
    name: "Carmel's Purple switch"
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms

sensor:
  - <<: !include common/sensor/wifi_signal.yaml
  - <<: !include common/sensor/uptime.yaml

status_led:
  pin:
    number: 2
    inverted: true
