substitutions:
  ip_address: !secret carmels_control_panel_ip
  reboot_time: 10min
  devicename: carmels-control-panel
  friendly_name: Carmel's Control Panel

packages:
  wifi: !include common/wifi.yaml

esphome:
  name: $devicename
  platform: ESP32
  board: esp-wrover-kit

  # Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:

binary_sensor:
  - <<: !include common/binary_sensor/status.yaml

  - platform: gpio
    pin:
      number: 23
      mode: INPUT_PULLUP
      inverted: true
    name: "Carmel's Green switch"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: 22
      mode: INPUT_PULLUP
      inverted: true
    name: "Carmel's Orange switch"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: 21
      mode: INPUT_PULLUP
      inverted: true
    name: "Carmel's Red switch"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: 19
      mode: INPUT_PULLUP
      inverted: true
    name: "Carmel's Blue switch"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: 18
      mode: INPUT_PULLUP
      inverted: true
    name: "Carmel's Purple switch"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

sensor:
  - <<: !include common/sensor/wifi_signal.yaml
  - <<: !include common/sensor/uptime.yaml

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:C7:7D:64"
    bindkey: "d25787b647b14c66f5aceb95f1a33570"
    temperature:
      name: "Emma's Room Temperature"
    humidity:
      name: "Emma's Room Humidity"
    battery_level:
      name: "Emma's Room Temp Sensor Battery Level"

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:3E:41:7D"
    bindkey: "d25787b647b14c66f5aceb95f1a33570"
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
    battery_level:
      name: "Bedroom Temp Sensor Battery Level"

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:40:77:6F"
    bindkey: "d25787b647b14c66f5aceb95f1a33570"
    temperature:
      name: "Bathroom Temperature"
    humidity:
      name: "Bathroom Humidity"
    battery_level:
      name: "Bathroom Temp Sensor Battery Level"

status_led:
  pin:
    number: 2
    inverted: true
