substitutions:
  ip_address: !secret ir-blaster_ip
  reboot_time: 10min
  devicename: ir-blaster
  friendly_name: IR Blaster

packages:
  wifi: !include common/wifi.yaml

esphome:
  name: $devicename
  platform: ESP32
  board: esp32dev

wifi:
  ap:
    password: !secret ap-password

captive_portal:
# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: blast_lg
      variables:
        blast_data: int
        blast_nbits: int
      then:
        - remote_transmitter.transmit_lg:
            data: !lambda 'return blast_data;'
            nbits: !lambda 'return blast_nbits;'

ota:

remote_receiver:
  pin:
    number: 4
    inverted: True
    mode: INPUT_PULLUP
  dump: all
  idle: 25ms

remote_transmitter:
  pin:
    number: 32
  carrier_duty_percent: 40%

switch:
  - platform: gpio
    pin: 13
    name: $friendly_name Receiver
    on_turn_on:
      then:
        - output.turn_on: blue_led
    on_turn_off:
      then:
        - output.turn_off: blue_led

status_led:
  pin:
    number: 26
    inverted: false

output:
  - platform: gpio
    pin: 5
    id: blue_led
