substitutions:
  devicename: kitchen-socket-2
  friendly_name: Kitchen Socket 2
  ip_address: !secret kitchen_socket_2_ip
  reboot_time: 0s

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/bseed_socket.yaml
