substitutions:
  devicename: kitchen_socket_2
  friendly_name: Kitchen Socket 2
  ip_address: 192.168.1.51
  reboot_time: 0s

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/bseed_socket.yaml
