substitutions:
  devicename: sink-light-shelly1
  friendly_name: Sink Light
  $reboot_time: 0s
  ip_address: !secret sink_light_ip

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/shelly1_light.yaml
