substitutions:
  devicename: emmas-ceiling-light-sonoff
  friendly_name: Emmas Ceiling Light
  reboot_time: 20min
  ip_address: !secret emmas_ceiling_light_ip

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/sonoff_basic_light.yaml
