substitutions:
  devicename: sitting-room-wall-light-shelly1
  friendly_name: Sitting Room Wall Lights
  $reboot_time: 0s
  ip_address: !secret sitting_room_wall_light_ip

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/shelly1_light.yaml
