substitutions:
  devicename: cooker-light-shelly1
  friendly_name: Cooker Light
  $reboot_time: 0s
  ip_address: !secret cooker_light_ip

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/shelly1_light.yaml
