substitutions:
  devicename: sitting-room-light-shelly1
  friendly_name: Sitting Room Light
  $reboot_time: 0s
  ip_address: !secret sitting_room_light_ip

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/shelly1_light.yaml
