substitutions:
  devicename: bedroom-ceiling-light-sonoff
  friendly_name: Bedroom Ceiling Light
  reboot_time: 20min
  ip_address: !secret bedroom_ceiling_light_ip

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/sonoff_basic_light.yaml

# wifi:
#   use_address: 192.168.1.30
