substitutions:
  devicename: carmels-bedside-light-sonoff
  friendly_name: Carmels Bedside Light
  reboot_time: 20min
  ip_address: !secret carmels_bedside_light_ip

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/sonoff_basic_light.yaml
