substitutions:
  devicename: landing-light-sonoff
  friendly_name: Landing Light
  reboot_time: 20min
  ip_address: !secret landing_light_ip

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/sonoff_basic_light.yaml

# wifi:
#   use_address: 192.168.1.25
