substitutions:
  devicename: jennys-bedside-light-sonoff
  friendly_name: Jennys Bedside Light
  reboot_time: 20min
  ip_address: !secret jennys_bedside_light_ip

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/sonoff_basic_light.yaml

# <<: !include common/sonoff_basic_light.yaml
