substitutions:
  devicename: emmas-bedside-light-sonoff
  friendly_name: Emmas Bedside Light
  reboot_time: 20min
  ip_address: !secret emmas_bedside_light_ip

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/sonoff_basic_light.yaml

# wifi:
#   use_address: 192.168.1.27
