substitutions:
  ip_address: 192.168.1.90
  reboot_time: 15min

esphome:
  name: pigeon_clock_in
  platform: ESP32
  board: esp-wrover-kit
packages:
  wifi: !include common/wifi.yaml

captive_portal:

logger:

# Enable Home Assistant API
api:

ota:

uart:
  rx_pin: 18
  baud_rate: 9600

rdm6300:
  on_tag:
    then:
      - sensor.template.publish:
          id: pigeon_ring
          state: !lambda 'return x;'

sensor:
  platform: template
  name: "Pigeon Ring"
  accuracy_decimals: 0
  id: pigeon_ring
  force_update: true
  lambda: return {};
