substitutions:
  devicename: doorbell
  friendly_name: Doorbell
  ip_address: 10.12.21.19
  line1_input_text: input_text.doorbell_line1
  line2_input_text: input_text.doorbell_line2
  reboot_time: 15min

esphome:
  name: $devicename
  platform: ESP32
  board: esp-wrover-kit
  # arduino_version: 1.0.5
  #   on_loop:
  #     then:
  #     if:
  #       condition:
  #         lambda: |-
  #           return (id(line1).state == "") and (id(line2).state == "");
  #       then:
  #         if:
  #           condition:
  #             binary_sensor.is_on: motion
  #           then:
  #             - display.page.show: time_page
  #             - component.update: lcd
  #           else:
  #             - display.page.show: blank_page
  #             - component.update: lcd
  #       else:
  #         - display.page.show: message_page
  #         - component.update: lcd

packages:
  wifi: !include common/wifi.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin: GPIO33
    name: $friendly_name PIR
    device_class: motion
    id: motion
    filters:
      delayed_off: 4s

  - platform: gpio
    pin:
      number: GPIO34
      inverted: true
    name: $friendly_name Button
    id: button

  - platform: status
    name: $friendly_name Status

sensor:
  - <<: !include common/sensor/wifi_signal.yaml
  - <<: !include common/sensor/uptime.yaml

esp32_camera:
  name: $friendly_name Camera
  external_clock:
    pin: GPIO32
    frequency: 20MHz
  i2c_pins:
    sda: GPIO13
    scl: GPIO12
  data_pins: [GPIO5, GPIO14, GPIO4, GPIO15, GPIO18, GPIO23, GPIO36, GPIO39]
  vsync_pin: GPIO27
  href_pin: GPIO25
  pixel_clock_pin: GPIO19
  power_down_pin: GPIO26
  resolution: 640x480
  jpeg_quality: 10
  vertical_flip: false
  horizontal_mirror: false
  brightness: 1

i2c:
  sda: GPIO21
  scl: GPIO22

# font:
#   - file: "common/fonts/times-new-roman.ttf"
#     id: tnr1
#     size: 20
#   - file: "common/fonts/times-new-roman.ttf"
#     id: tnr2
#     size: 35

# time:
#   - platform: homeassistant
#     id: homeassistant_time

# text_sensor:
#   - platform: homeassistant
#     entity_id: $line1_input_text
#     internal: true
#     id: line1

#   - platform: homeassistant
#     entity_id: $line2_input_text
#     internal: true
#     id: line2

# display:
#   - platform: ssd1306_i2c
#     model: "SSD1306 128x64"
#     address: 0x3C
#     id: lcd
#     pages:
#       - id: blank_page
#         lambda: |-
#           it.fill(COLOR_OFF);
#       - id: time_page
#         lambda: |-
#           it.strftime(64, 0, id(tnr2), TextAlign::TOP_CENTER,"%d-%m-%Y", id(homeassistant_time).now());
#           it.strftime(64, 64, id(tnr2), TextAlign::BASELINE_CENTER, "%H:%M", id(homeassistant_time).now());
#       - id: message_page
#         lambda: |-
#           it.printf(64, 0, id(tnr1), TextAlign::TOP_CENTER, " %s", id(line1).state.c_str());
#           it.printf(64, 64, id(tnr1), TextAlign::BASELINE_CENTER, " %s", id(line2).state.c_str());

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
