automation:
  - id: '52c99e93-e48a-4cc0-a63f-7c1d9b270947'
    alias: OS Update Notification
    trigger:
      - platform: state
        entity_id: update.home_assistant_operating_system_update
      - platform: homeassistant
        event: start
    action:
      - if:
        - alias: "Update Available"
          condition: state
          entity_id: update.home_assistant_operating_system_update
          state: 'on'
        then:
          - service: notify.mobile_app_jenny_s_phone
            data:
              message: >
                There is an update to Home Assistant OS:
                  * {{ state_attr("update.home_assistant_operating_system_update", installed_version) }} -> {{ state_attr("update.home_assistant_operating_system_update", "latest_version") }}
              title: OS Update Available
              data:
                sticky: 'true'
                group: updates
                tag: update_os
                color: '#ff8c00'
                clickAction: /hasio/dashboard
          - service: persistent_notification.create
            data:
              title: OS Update Available
              message: >-
                There is an update to Home Assistant OS:
                  * {{ state_attr("update.home_assistant_operating_system_update", installed_version) }} -> {{ state_attr("update.home_assistant_operating_system_update", "latest_version") }}
              notification_id: update_os
        else:
          - service: notify.mobile_app_jenny_s_phone
            data:
              message: clear_notification
              data:
                tag: update_os
          - service: persistent_notification.dismiss
            data:
              notification_id: update_os
