readme:

automation:
  - id: '0a55daf1-ea12-4fbe-951d-39c33b80ae51'
    alias: Generate readme
    trigger:
      - platform: homeassistant
        event: start
    action:
      - wait_for_trigger:
          - platform: event
            event_type: hacs/stage
            event_data:
              stage: running
        timeout:
          minutes: 5
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ not wait.trigger }}"
            sequence:
              # Timeout reached
              - service: persistent_notification.create
                data:
                  title: ReadMe generation failed!
                  message: Timeout reached! Hacs could not start in time.
        default:
          - service: readme.generate
