sensor:
  - platform: hp_ilo
    host: !secret ilo_host
    username: !secret ilo_user
    password: !secret ilo_password
    scan_interval: 60
    monitored_variables:
      - name: Power
        sensor_type: server_power_status  # Whether the server is powered on or not.
      - name: Power Current
        sensor_type: server_power_readings  # Get current, min, max and average power readings.
        value_template: '{{ ilo_data.present_power_reading.0 | int}}'
        unit_of_measurement: "W"
      - name: Power Max
        sensor_type: server_power_readings  # Get current, min, max and average power readings.
        value_template: '{{ ilo_data.maximum_power_reading.0 | int }}'
        unit_of_measurement: "W"
      - name: Power Min
        sensor_type: server_power_readings  # Get current, min, max and average power readings.
        value_template: '{{ ilo_data.minimum_power_reading.0 | int }}'
        unit_of_measurement: "W"
      - name: Power Average
        sensor_type: server_power_readings  # Get current, min, max and average power readings.
        value_template: '{{ ilo_data.average_power_reading.0 | int}}'
        unit_of_measurement: "W"
      - name: power on time
        unit_of_measurement: min
        sensor_type: server_power_on_time  # How many minutes ago has the server been powered on (Non-resetting counter, akin to hours used).
      - name: uid Light
        sensor_type: server_uid_status  # Get the status of the UID light.
      - name: fan 1 speed
        sensor_type: server_health
        unit_of_measurement: "%"
        value_template: '{{ ilo_data.fans["Fan 1"].speed.0 }}'
      - name: fan 2 speed
        sensor_type: server_health
        unit_of_measurement: "%"
        value_template: '{{ ilo_data.fans["Fan 2"].speed.0 }}'
      - name: fan 3 speed
        sensor_type: server_health
        unit_of_measurement: "%"
        value_template: '{{ ilo_data.fans["Fan 3"].speed.0 }}'
      - name: fan 4 speed
        sensor_type: server_health
        unit_of_measurement: "%"
        value_template: '{{ ilo_data.fans["Fan 4"].speed.0 }}'
      - name: fan 5 speed
        sensor_type: server_health
        unit_of_measurement: "%"
        value_template: '{{ ilo_data.fans["Fan 5"].speed.0 }}'
      - name: fan 6 speed
        sensor_type: server_health
        unit_of_measurement: "%"
        value_template: '{{ ilo_data.fans["Fan 6"].speed.0 }}'
      - name: Temperature Inlet
        sensor_type: server_health
        unit_of_measurement: "°C"
        value_template: '{{ ilo_data.temperature["01-Front Ambient"].currentreading[0] }}'
      - name: Temperature Exhaust
        sensor_type: server_health
        unit_of_measurement: "°C"
        value_template: '{{ ilo_data.temperature["48-Sys Exhaust"].currentreading[0] }}'
      - name: Temperature PS1
        sensor_type: server_health
        unit_of_measurement: "°C"
        value_template: '{{ ilo_data.temperature["15-P/S 1"].currentreading[0] }}'
      - name: Temperature PS2
        sensor_type: server_health
        unit_of_measurement: "°C"
        value_template: '{{ ilo_data.temperature["16-P/S 2"].currentreading[0] }}'
      - name: Temperature CPU 1
        sensor_type: server_health
        unit_of_measurement: "°C"
        value_template: '{{ ilo_data.temperature["02-CPU 1"].currentreading[0] }}'
      - name: Temperature CPU 2
        sensor_type: server_health
        unit_of_measurement: "°C"
        value_template: '{{ ilo_data.temperature["03-CPU 2"].currentreading[0] }}'
      - name: Temperature Raid Card
        sensor_type: server_health
        unit_of_measurement: "°C"
        value_template: '{{ ilo_data.temperature["31-PCI 3"].currentreading[0] }}'
      - name: Health Bios
        sensor_type: server_health
        value_template: '{{ ilo_data.health_at_a_glance["bios_hardware"].status }}'
      - name: Health Fans
        sensor_type: server_health
        value_template: '{{ ilo_data.health_at_a_glance["fans"].status }}'
      - name: Health Memory
        sensor_type: server_health
        value_template: '{{ ilo_data.health_at_a_glance["memory"].status }}'
      - name: Health Network
        sensor_type: server_health
        value_template: '{{ ilo_data.health_at_a_glance["network"].status }}'
      - name: Health Processor
        sensor_type: server_health
        value_template: '{{ ilo_data.health_at_a_glance["processor"].status }}'
      - name: Health Storage
        sensor_type: server_health
        value_template: '{{ ilo_data.health_at_a_glance["storage"].status }}'
      - name: Health Temperature
        sensor_type: server_health
        value_template: '{{ ilo_data.health_at_a_glance["temperature"].status }}'
      - name: Health PS 1
        sensor_type: server_health
        value_template: '{{ ilo_data.power_supplies["Power Supply 1"].status }}'
      - name: Health PS 2
        sensor_type: server_health
        value_template: '{{ ilo_data.power_supplies["Power Supply 2"].status }}'

  - platform: integration
    source: sensor.hp_ilo_power_current
    name: Server energy use
    unit_prefix: k
    round: 2

command_line:
  - binary_sensor:
      unique_id: '22b8b2a2-7eff-4796-853d-299940ba1b80'
      name: Zpool Rpool Problem
      command: !secret zpool_rpool_status_command
      value_template: >-
        {% if value == "state: ONLINE" %}
          OFF
        {% else %}
          ON
        {% endif %}
      device_class: problem

homeassistant:
  customize:
    sensor.server_energy_use:
      device_class: energy

shell_command:
  hp_ilo_adjust_fan_pid_controller_30: !secret hp_ilo_adjust_fan_pid_controller_30
  hp_ilo_adjust_fan_pid_controller_43: !secret hp_ilo_adjust_fan_pid_controller_43
  hp_ilo_adjust_fan_pid_controller_44: !secret hp_ilo_adjust_fan_pid_controller_44
  # hp_ilo_adjust_fan_1_min_speed: !secret hp_ilo_adjust_fan_1_min_speed
  # hp_ilo_adjust_fan_2_min_speed: !secret hp_ilo_adjust_fan_2_min_speed
  # hp_ilo_adjust_fan_3_min_speed: !secret hp_ilo_adjust_fan_3_min_speed
  # hp_ilo_adjust_fan_4_min_speed: !secret hp_ilo_adjust_fan_4_min_speed
  # hp_ilo_adjust_fan_5_min_speed: !secret hp_ilo_adjust_fan_5_min_speed
  # hp_ilo_adjust_fan_6_min_speed: !secret hp_ilo_adjust_fan_6_min_speed

automation:
  - id: "7ee66689-e490-47ca-a4df-bae4c350bea6"
    alias: Server Fan Adjustments
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: shell_command.hp_ilo_adjust_fan_pid_controller_30
      - service: shell_command.hp_ilo_adjust_fan_pid_controller_43
      - service: shell_command.hp_ilo_adjust_fan_pid_controller_44
      # - service: shell_command.hp_ilo_adjust_fan_1_min_speed
      # - service: shell_command.hp_ilo_adjust_fan_2_min_speed
      # - service: shell_command.hp_ilo_adjust_fan_3_min_speed
      # - service: shell_command.hp_ilo_adjust_fan_4_min_speed
      # - service: shell_command.hp_ilo_adjust_fan_5_min_speed
      # - service: shell_command.hp_ilo_adjust_fan_6_min_speed


  - id: "ab5a8d92-6227-4fd9-961f-e4e69f4c90d7"
    alias: Zpool problem notification
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.zpool_rpool_problem
        for: "00:05:00"
    action:
      - if:
          # zpool issues present - send notification
          - alias: "zpool issues present"
            condition: state
            entity_id: binary_sensor.zpool_rpool_problem
            state: "on"
        then:
          - service: notify.mobile_app_jenny_s_phone
            data:
              message: >-
                Problem detected with:
                {% for state in (states.binary_sensor.zpool_rpool_problem) | selectattr("state", "equalto", "on") -%}
                • {{(state.name).split(" ").1}}
                {% endfor %}
              title: Zpool Issue
              data:
                sticky: 'true'
                tag: zpool_issue
                group: server
                color: '#FF0000'
        else:
          # no zpool issues - clear notification
          - service: notify.mobile_app_jenny_s_phone
            data:
              message: clear_notification
              data:
                tag: zpool_issue
