automation:
  - id: 'ef8b316b-02fa-4470-b336-095cfc9a074b'
    alias: Supervisor Update Notification
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: update.home_assistant_supervisor_update
    action:
      - if:
        - alias: "Update Available"
          condition: state
          entity_id: sensor.supervisor_update
          state: 'on'
        then:
          - service: notify.mobile_app_jenny_s_phone
            data:
              message: >
                There is an updates to Home Assistant Supervisor:
                * {{ state_attr("update.home_assistant_supervisor_update", "installed_version") }} -> {{ state_attr("update.home_assistant_supervisor_update", "latest_version") }}
              title: Supervisor Update Available
              data:
                sticky: 'true'
                group: updates
                tag: update_supervisor
                color: '#ff8c00'
                clickAction: /hasio/dashboard
          - service: persistent_notification.create
            data:
              title: OS Update Available
              message: >-
                There is an update to Home Assistant Supervisor:
                  * {{ state_attr("update.home_assistant_supervisor_update", installed_version) }} -> {{ state_attr("update.home_assistant_supervisor_update", "latest_version") }}
              notification_id: update_supervisor
        else:
          - service: notify.mobile_app_jenny_s_phone
            data:
              message: clear_notification
              data:
                tag: update_supervisor
          - service: persistent_notification.dismiss
            data:
              notification_id: update_supervisor
